# Generated by Django 4.0.4 on 2022-06-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_seller_photo_alter_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
    ]
