# Generated by Django 4.0.4 on 2022-06-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_seller_email'),
        ('menu', '0003_alter_product_options_type_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
        migrations.AlterField(
            model_name='type',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
    ]
