# Generated by Django 4.0.4 on 2022-06-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_product_image_delete_poducts_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['publication_date']},
        ),
        migrations.AlterField(
            model_name='product',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
